# https://docs.github.com/en/actions/tutorials/create-actions/create-a-composite-action

name: upload-test results
description: upload-test results

runs:
  using: composite
  steps:
    - name: "upload / test results"
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: test-results
        path: |
          **/build/test-results/test/TEST-*.xml
